"""
here are the labels used by the different software i evaluate writen as dictionary.
"""
label_cnn = {
    0: 'BG',
    12: 'CM',
    33: 'R_I-III',
    36: 'L_I-III',
    43: 'R_IV',
    46: 'L_IV',
    53: 'R_V',
    56: 'L_V',
    60: 'R_VI',
    63: 'V_VI',
    66: 'L_VI',
    70: 'V_VII',
    73: 'R_CRI',
    74: 'R_CRII',
    75: 'R_VIIB',
    76: 'L_CRI',
    77: 'L_CRII',
    78: 'L_VIIB',
    80: 'V_VIII',
    83: 'R_VIIIA',
    84: 'R_VIIIB',
    86: 'L_VIIIA',
    87: 'L_VIIIB',
    90: 'V_IX',
    93: 'R_IX',
    96: 'L_IX',
    100: 'V_X',
    103: 'R_X',
    106: 'L_X'
}
label_suit = {
    0: 'BG',
    1: 'L_I-IV',
    2: 'R_I-IV',
    3: 'L_V',
    4: 'R_V',
    5: 'L_VI',
    6: 'V_VI',
    7: 'R_VI',
    8: 'L_CrusI',
    9: 'V_CrusI',
    10: 'R_CrusI',
    11: 'L_CrusII',
    12: 'V_CrusII',
    13: 'R_CrusII',
    14: 'L_VIIb',
    15: 'V_VIIb',
    16: 'R_VIIb',
    17: 'L_VIIIa',
    18: 'V_VIIIa',
    19: 'R_VIIIa',
    20: 'L_VIIIb',
    21: 'V_VIIIb',
    22: 'R_VIIIb',
    23: 'L_IX',
    24: 'V_IX',
    25: 'R_IX',
    26: 'L_X',
    27: 'V_X',
    28: 'R_X',
    29: 'L_Dentate',
    30: 'R_Dentate',
    31: 'L_Interposed',
    32: 'R_Interposed',
    33: 'L_Fastigial',
    34: 'R_Fastigial'
}

label_suiter = {
    0: 'BG',
    1: 'L_I-IV',
    2: 'R_I-IV',
    3: 'L_V',
    4: 'R_V',
    5: 'L_VI',
    6: 'V_VI',
    7: 'R_VI',
    8: 'L_CrusI',
    9: 'V_CrusI',
    10: 'R_CrusI',
    11: 'L_CrusII',
    12: 'V_CrusII',
    13: 'R_CrusII',
    14: 'L_VIIb',
    15: 'V_VIIb',
    16: 'R_VIIb',
    17: 'L_VIIIa',
    18: 'V_VIIIa',
    19: 'R_VIIIa',
    20: 'L_VIIIb',
    21: 'V_VIIIb',
    22: 'R_VIIIb',
    23: 'L_IX',
    24: 'V_IX',
    25: 'R_IX',
    26: 'L_X',
    27: 'V_X',
    28: 'R_X',
    29: 'L_Dentate',
    30: 'R_Dentate',
    31: 'L_Interposed',
    32: 'R_Interposed',
    33: 'L_Fastigial',
    34: 'R_Fastigial'
}


